# Jekyll configuration

name: Đăng Trung IT
description: Blog chuyên về công nghệ thông tin và những vấn đề xung quanh

# Url is currently only used only for the RSS feed in feed.xml
url: http://dangtrungit.tk

github_url: https://hoangdangtrungvn.github.io

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: ''

facebook:
  app_id: 780023325485241

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github:
  facebook: trung.tk43.utehy
  linkedin:
  instagram:
  lastfm:
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:

# permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: "/blog/page:num/"

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
